### ISSUE TITLE
CreaturePack build error on Clang/Linux

### ISSUE THREAD

**Issue by NuLL3rr0r** [kestrelm/Creature_UE4#21]
Hi,

I'm trying out Creature on UE4/Clang/Linux and I got CreaturePlugin with [a bit of modification](https://github.com/kestrelm/Creature_UE4/pull/20) to build on Clang/Linux. Unfortunately, CreaturePack has build issues too and gives me the following build error:

```
LogCompile: /path/to/some/project/Plugins/CreaturePlugin/Source/CreaturePlugin/Public/CustomProceduralMeshComponent.h(105): Error: struct: 'ProceduralMeshVertex' conflicts with class name Error: struct: 'ProceduralMeshVertex' conflicts with class name

Error: UnrealHeaderTool failed for target 'SomeProject' (platform: Linux, module info: LogInit:Warning: Still incompatible or missing module: libUE4Editor-CreaturePackRuntimePlugin.so
LogInit:Warning: Still incompatible or missing module: libUE4Editor-CreaturePackEditor.so
```

By the way, I'm not sure what is the difference between CreaturePlugin and CreaturePack and why adding CreaturePack causes build error inside CreaturePlugin.

**Comment by kestrelm** [comment]
Hello,

You only use CreaturePack if you want a pure point cache playback of Creature characters.
Please read:
https://github.com/kestrelm/Creature_UE4/tree/master/CreaturePackPlugin

To learn about the difference. Are both plugins built in the same project? That might be the reason for the naming conflict. I will look into renaming one the ProceduralMeshVertex objects sometime to avoid this conflict. That is my guess since ProceduralMeshVertex also exists in CreaturePlugin.

**Comment by kestrelm** [comment]
@NuLL3rr0r Another update: I just checked in a change to CreaturePack, renaming the vertex and triangle data structures. I successfully included both plugins into a project and it built through.

**Comment by NuLL3rr0r** [comment]
Thank you so much for the quick fix. I tried to build the both plugins in one project and it builds just fine.

And, thanks for this awesome 2D tool and the extra information :)
